// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace WebFamily.Server.Models;

public partial class AmericanMusicsDirectoryView
{
    public string Directory { get; set; }
}