// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace WebFamily.Server.Models;

public partial class AmericanMusicsView
{
    public string? Name { get; set; }

    public string? Directory { get; set; }

    public string Title { get; set; } = null!;

    public string Type { get; set; } = null!;

    public string? Duration { get; set; }

    public DateTime Datetime { get; set; }
}