// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebFamily.Models;

public partial class AmericanMusicsView
{
    public string Name { get; set; }

    public string Directory { get; set; }

    public string Title { get; set; }

    public string Type { get; set; }

    public string Duration { get; set; }

    public DateTime Datetime { get; set; }

    public string Caption { get; set; }
}