// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace WebFamily.Server.Models;

public partial class MediaTrack
{
    public Guid RecordId { get; set; }

    public Guid FolderId { get; set; }

    public string FileName { get; set; } = null!;

    public string? Title { get; set; }

    public string? Artist { get; set; }

    public string? Album { get; set; }

    public int? TrackNumber { get; set; }

    public int? Year { get; set; }

    public string? Genre { get; set; }

    public string? Duration { get; set; }

    public string Type { get; set; } = null!;

    public DateTime Datetime { get; set; }

    public virtual MediaFolder Folder { get; set; } = null!;

    public virtual ICollection<MediaSubtitle> MediaSubtitles { get; set; } = new List<MediaSubtitle>();
}