// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebFamily.Models;

public partial class MediaMenu
{
    public Guid RecordId { get; set; }

    public string Menu { get; set; }

    public DateTime Datetime { get; set; }

    public virtual ICollection<MediaDirectory> MediaDirectories { get; set; } = new List<MediaDirectory>();
}