// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebFamily.Models;

public partial class MediaView
{
    public string Type { get; set; }

    public string Title { get; set; }

    public Guid DirectoryId { get; set; }

    public Guid RecordId { get; set; }

    public string Directory { get; set; }

    public Guid? MenuId { get; set; }

    public string Menu { get; set; }
    public string Duration { get; set; }
}