// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace WebFamily.Server.Models;

public partial class MediaFolderListView
{
    public string Name { get; set; } = null!;
}