// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebFamily.Models;

public partial class MediaMetaDatum
{
    public Guid RecordId { get; set; }

    public Guid DirectoryId { get; set; }

    public string Title { get; set; }

    public string Type { get; set; }

    public string Caption { get; set; }

    public DateTime Datetime { get; set; }

    public string Duration { get; set; }

    public virtual MediaDirectory Directory { get; set; }
}