// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace WebFamily.Server.Models;

public partial class MediaMenu
{
    public Guid RecordId { get; set; }

    public string Menu { get; set; } = null!;

    public DateTime Datetime { get; set; }

    public virtual ICollection<MediaFolder> MediaFolders { get; set; } = new List<MediaFolder>();
}