// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace WebFamily.Server.Models;

public partial class MediaEndItemView
{
    public Guid FolderId { get; set; }

    public Guid MenuId { get; set; }

    public string Name { get; set; } = null!;

    public string? CoverImagePath { get; set; }
}