// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebFamily.Models;

public partial class MediaDirectory
{
    public Guid RecordId { get; set; }

    public Guid MenuId { get; set; }

    public string Directory { get; set; }

    public DateTime Datetime { get; set; }

    public virtual ICollection<MediaMetaDatum> MediaMetaData { get; set; } = new List<MediaMetaDatum>();

    public virtual MediaMenu Menu { get; set; }
}