// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace WebFamily.Server.Models;

public partial class MediaSubtitle
{
    public Guid MediaMetaDataRecordId { get; set; }

    public Guid RecordId { get; set; }

    public string Language { get; set; } = null!;

    public string Label { get; set; } = null!;

    public string FileName { get; set; } = null!;

    public bool IsDefault { get; set; }

    public virtual MediaTrack MediaMetaDataRecord { get; set; } = null!;
}