// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace WebFamily.Server.Models;

public partial class MediaMetaDatum
{
    public Guid RecordId { get; set; }

    public Guid DirectoryId { get; set; }

    public string Title { get; set; } = null!;

    public string Type { get; set; } = null!;

    public DateTime Datetime { get; set; }

    public string? Duration { get; set; }

    public virtual MediaDirectory Directory { get; set; } = null!;

    public virtual ICollection<MediaSubtitle> MediaSubtitles { get; set; } = new List<MediaSubtitle>();
}