// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace WebFamily.Server.Models;

public partial class Rpm
{
    public Guid RecordId { get; set; }

    public string Title { get; set; }

    public string Type { get; set; }

    public string AudioType { get; set; }

    public DateTime DateTime { get; set; }

    /// <summary>
    /// Album-level artist. For compilation/multi-artist discs, individual
    /// tracks can override this via RpmTrack.Artist; this is the fallback
    /// shown when a track has no override.
    /// </summary>
    public string Artist { get; set; }

    public virtual ICollection<RpmTrack> RpmTracks { get; set; } = new List<RpmTrack>();
}