// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebFamily.Models;

public partial class Rpm
{
    public Guid RecordId { get; set; }

    public string Title { get; set; }

    public string Type { get; set; }

    public string AudioType { get; set; }

    public DateTime DateTime { get; set; }

    public virtual ICollection<RpmTrack> RpmTracks { get; set; } = new List<RpmTrack>();
}