// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace WebFamily.Server.Models;

public partial class RpmTrack
{
    public Guid RecordId { get; set; }

    public Guid RpmId { get; set; }

    public string Title { get; set; }

    public DateTime DateTime { get; set; }

    /// <summary>
    /// Track duration in whole seconds, read from the audio file itself
    /// (TagLib) during regen. Null if it couldn't be determined.
    /// </summary>
    public int? DurationSeconds { get; set; }

    /// <summary>
    /// 1-based track order, parsed from the source file name during regen
    /// (see TrackTitleParser). Null if no track number could be parsed.
    /// </summary>
    public int? TrackNumber { get; set; }

    /// <summary>
    /// Per-track artist override for compilation/multi-artist discs. Null
    /// means "use Rpm.Artist".
    /// </summary>
    public string Artist { get; set; }

    public virtual Rpm Rpm { get; set; }
}