// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebFamily.Models;

public partial class TodoList
{
    public Guid RecordId { get; set; }

    public DateTime DueDate { get; set; }

    public string Note { get; set; }

    public string Assigned { get; set; }

    public DateTime DateTime { get; set; }

}