// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace WebFamily.Server.Models;

public partial class WebFamilyDbContext : DbContext
{
    public WebFamilyDbContext(DbContextOptions<WebFamilyDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AspNetRole> AspNetRoles { get; set; }

    public virtual DbSet<AspNetRoleClaim> AspNetRoleClaims { get; set; }

    public virtual DbSet<AspNetUser> AspNetUsers { get; set; }

    public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }

    public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }

    public virtual DbSet<AspNetUserToken> AspNetUserTokens { get; set; }

    public virtual DbSet<MediaEndItemView> MediaEndItemViews { get; set; }

    public virtual DbSet<MediaFolder> MediaFolders { get; set; }

    public virtual DbSet<MediaFolderListView> MediaFolderListViews { get; set; }

    public virtual DbSet<MediaMenu> MediaMenus { get; set; }

    public virtual DbSet<MediaSubtitle> MediaSubtitles { get; set; }

    public virtual DbSet<MediaTrack> MediaTracks { get; set; }

    public virtual DbSet<Rpm> Rpms { get; set; }

    public virtual DbSet<RpmTrack> RpmTracks { get; set; }

    public virtual DbSet<TodoList> TodoLists { get; set; }

    public virtual DbSet<WebTube> WebTubes { get; set; }

    public virtual DbSet<WebTubeSeries> WebTubeSeries { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<AspNetRole>(entity =>
        {
            entity.HasIndex(e => e.NormalizedName, "RoleNameIndex")
                .IsUnique()
                .HasFilter("([NormalizedName] IS NOT NULL)");

            entity.Property(e => e.Name).HasMaxLength(256);
            entity.Property(e => e.NormalizedName).HasMaxLength(256);
        });

        modelBuilder.Entity<AspNetRoleClaim>(entity =>
        {
            entity.HasIndex(e => e.RoleId, "IX_AspNetRoleClaims_RoleId");

            entity.HasOne(d => d.Role).WithMany(p => p.AspNetRoleClaims).HasForeignKey(d => d.RoleId);
        });

        modelBuilder.Entity<AspNetUser>(entity =>
        {
            entity.HasIndex(e => e.NormalizedEmail, "EmailIndex");

            entity.HasIndex(e => e.NormalizedUserName, "UserNameIndex")
                .IsUnique()
                .HasFilter("([NormalizedUserName] IS NOT NULL)");

            entity.Property(e => e.Email).HasMaxLength(256);
            entity.Property(e => e.NormalizedEmail).HasMaxLength(256);
            entity.Property(e => e.NormalizedUserName).HasMaxLength(256);
            entity.Property(e => e.UserName).HasMaxLength(256);

            entity.HasMany(d => d.Roles).WithMany(p => p.Users)
                .UsingEntity<Dictionary<string, object>>(
                    "AspNetUserRole",
                    r => r.HasOne<AspNetRole>().WithMany().HasForeignKey("RoleId"),
                    l => l.HasOne<AspNetUser>().WithMany().HasForeignKey("UserId"),
                    j =>
                    {
                        j.HasKey("UserId", "RoleId");
                        j.ToTable("AspNetUserRoles");
                        j.HasIndex(new[] { "RoleId" }, "IX_AspNetUserRoles_RoleId");
                    });
        });

        modelBuilder.Entity<AspNetUserClaim>(entity =>
        {
            entity.HasIndex(e => e.UserId, "IX_AspNetUserClaims_UserId");

            entity.HasOne(d => d.User).WithMany(p => p.AspNetUserClaims).HasForeignKey(d => d.UserId);
        });

        modelBuilder.Entity<AspNetUserLogin>(entity =>
        {
            entity.HasKey(e => new { e.LoginProvider, e.ProviderKey });

            entity.HasIndex(e => e.UserId, "IX_AspNetUserLogins_UserId");

            entity.HasOne(d => d.User).WithMany(p => p.AspNetUserLogins).HasForeignKey(d => d.UserId);
        });

        modelBuilder.Entity<AspNetUserToken>(entity =>
        {
            entity.HasKey(e => new { e.UserId, e.LoginProvider, e.Name });

            entity.HasOne(d => d.User).WithMany(p => p.AspNetUserTokens).HasForeignKey(d => d.UserId);
        });

        modelBuilder.Entity<MediaEndItemView>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("MediaEndItemView");

            entity.Property(e => e.CoverImagePath)
                .HasMaxLength(500)
                .HasColumnName("coverImagePath");
            entity.Property(e => e.FolderId).HasColumnName("folderId");
            entity.Property(e => e.MenuId).HasColumnName("menuId");
            entity.Property(e => e.Name)
                .HasMaxLength(250)
                .HasColumnName("name");
        });

        modelBuilder.Entity<MediaFolder>(entity =>
        {
            entity.HasKey(e => e.RecordId).HasName("PK_folder");

            entity.ToTable("MediaFolder");

            entity.HasIndex(e => e.ParentFolderId, "IX_folder_parentFolderId");

            entity.HasIndex(e => new { e.MenuId, e.ParentFolderId, e.Name }, "UX_folder_parent_name").IsUnique();

            entity.Property(e => e.RecordId)
                .HasDefaultValueSql("(newid())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_folder_recordId")
                .HasColumnName("recordId");
            entity.Property(e => e.CoverImagePath)
                .HasMaxLength(500)
                .UseCollation("Latin1_General_100_BIN2")
                .HasColumnName("coverImagePath");
            entity.Property(e => e.Datetime)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_folder_datetime")
                .HasColumnType("datetime")
                .HasColumnName("datetime");
            entity.Property(e => e.MenuId).HasColumnName("menuId");
            entity.Property(e => e.Name)
                .HasMaxLength(250)
                .UseCollation("Latin1_General_100_BIN2")
                .HasColumnName("name");
            entity.Property(e => e.ParentFolderId).HasColumnName("parentFolderId");
            entity.Property(e => e.RootPath)
                .HasMaxLength(500)
                .HasColumnName("rootPath");

            entity.HasOne(d => d.Menu).WithMany(p => p.MediaFolders)
                .HasForeignKey(d => d.MenuId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_MediaFolder_MediaMenu");

            entity.HasOne(d => d.ParentFolder).WithMany(p => p.InverseParentFolder)
                .HasForeignKey(d => d.ParentFolderId)
                .HasConstraintName("FK_MediaFolder_MediaFolder_Parent");
        });

        modelBuilder.Entity<MediaFolderListView>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("MediaFolderListView");

            entity.Property(e => e.Name)
                .HasMaxLength(250)
                .HasColumnName("name");
        });

        modelBuilder.Entity<MediaMenu>(entity =>
        {
            entity.HasKey(e => e.RecordId);

            entity.ToTable("MediaMenu");

            entity.Property(e => e.RecordId)
                .HasDefaultValueSql("(newid())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_menu_recordId")
                .HasColumnName("recordId");
            entity.Property(e => e.Datetime)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_menu_datetime")
                .HasColumnType("datetime")
                .HasColumnName("datetime");
            entity.Property(e => e.Menu)
                .HasMaxLength(50)
                .HasColumnName("menu");
        });

        modelBuilder.Entity<MediaSubtitle>(entity =>
        {
            entity.HasKey(e => e.RecordId).HasName("PK__MediaSub__FBDF78E902AD87BA");

            entity.HasIndex(e => e.MediaMetaDataRecordId, "IX_MediaSubtitles_MediaMetaDataRecordId");

            entity.Property(e => e.RecordId)
                .HasDefaultValueSql("(newid())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_MediaSubtitles_RecordId");
            entity.Property(e => e.FileName).HasMaxLength(260);
            entity.Property(e => e.Label).HasMaxLength(50);
            entity.Property(e => e.Language).HasMaxLength(10);

            entity.HasOne(d => d.MediaMetaDataRecord).WithMany(p => p.MediaSubtitles)
                .HasForeignKey(d => d.MediaMetaDataRecordId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_MediaSubtitles_MediaTrack");
        });

        modelBuilder.Entity<MediaTrack>(entity =>
        {
            entity.HasKey(e => e.RecordId).HasName("PK_track");

            entity.ToTable("MediaTrack");

            entity.HasIndex(e => e.FolderId, "IX_track_folderId");

            entity.HasIndex(e => new { e.FolderId, e.FileName }, "UX_track_folder_fileName").IsUnique();

            entity.Property(e => e.RecordId)
                .HasDefaultValueSql("(newid())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_track_recordId")
                .HasColumnName("recordId");
            entity.Property(e => e.Album)
                .HasMaxLength(250)
                .UseCollation("Latin1_General_100_BIN2")
                .HasColumnName("album");
            entity.Property(e => e.Artist)
                .HasMaxLength(250)
                .UseCollation("Latin1_General_100_BIN2")
                .HasColumnName("artist");
            entity.Property(e => e.Datetime)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_track_datetime")
                .HasColumnType("datetime")
                .HasColumnName("datetime");
            entity.Property(e => e.Duration)
                .HasMaxLength(50)
                .HasColumnName("duration");
            entity.Property(e => e.FileName)
                .HasMaxLength(260)
                .UseCollation("Latin1_General_100_BIN2")
                .HasColumnName("fileName");
            entity.Property(e => e.FolderId).HasColumnName("folderId");
            entity.Property(e => e.Genre)
                .HasMaxLength(100)
                .UseCollation("Latin1_General_100_BIN2")
                .HasColumnName("genre");
            entity.Property(e => e.Title)
                .HasMaxLength(250)
                .UseCollation("Latin1_General_100_BIN2")
                .HasColumnName("title");
            entity.Property(e => e.TrackNumber).HasColumnName("trackNumber");
            entity.Property(e => e.Type)
                .HasMaxLength(150)
                .HasColumnName("type");
            entity.Property(e => e.Year).HasColumnName("year");

            entity.HasOne(d => d.Folder).WithMany(p => p.MediaTracks)
                .HasForeignKey(d => d.FolderId)
                .HasConstraintName("FK_MediaTrack_MediaFolder");
        });

        modelBuilder.Entity<Rpm>(entity =>
        {
            entity.HasKey(e => e.RecordId).HasName("PK_rpm");

            entity.ToTable("Rpm");

            entity.Property(e => e.RecordId)
                .HasDefaultValueSql("(newid())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_rpm_recordId")
                .HasColumnName("recordId");
            entity.Property(e => e.Artist)
                .HasMaxLength(250)
                .HasColumnName("artist");
            entity.Property(e => e.AudioType)
                .HasMaxLength(50)
                .HasColumnName("audioType");
            entity.Property(e => e.DateTime)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_rpm_dateTime")
                .HasColumnType("datetime")
                .HasColumnName("dateTime");
            entity.Property(e => e.Title)
                .HasMaxLength(250)
                .HasColumnName("title");
            entity.Property(e => e.Type)
                .HasMaxLength(50)
                .HasColumnName("type");
        });

        modelBuilder.Entity<RpmTrack>(entity =>
        {
            entity.HasKey(e => e.RecordId);

            entity.ToTable("RpmTrack");

            entity.Property(e => e.RecordId)
                .HasDefaultValueSql("(newid())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_RpmTrack_recordId")
                .HasColumnName("recordId");
            entity.Property(e => e.Artist)
                .HasMaxLength(250)
                .HasColumnName("artist");
            entity.Property(e => e.DateTime)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_RpmTrack_dateTime")
                .HasColumnType("datetime")
                .HasColumnName("dateTime");
            entity.Property(e => e.DurationSeconds).HasColumnName("durationSeconds");
            entity.Property(e => e.RpmId).HasColumnName("rpmId");
            entity.Property(e => e.Title)
                .HasMaxLength(250)
                .HasColumnName("title");
            entity.Property(e => e.TrackNumber).HasColumnName("trackNumber");

            entity.HasOne(d => d.Rpm).WithMany(p => p.RpmTracks)
                .HasForeignKey(d => d.RpmId)
                .HasConstraintName("FK_RpmTrack_rpm");
        });

        modelBuilder.Entity<TodoList>(entity =>
        {
            entity.HasKey(e => e.RecordId);

            entity.ToTable("TodoList");

            entity.Property(e => e.RecordId).ValueGeneratedNever();
            entity.Property(e => e.Assigned).HasMaxLength(50);
            entity.Property(e => e.DateTime)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Table_1_dateCreate")
                .HasColumnType("datetime");
            entity.Property(e => e.DueDate).HasColumnType("datetime");
        });

       
        modelBuilder.Entity<WebTube>(entity =>
        {
            entity.HasKey(e => e.RecordId);

            entity.ToTable("WebTube");

            entity.Property(e => e.RecordId)
                .HasDefaultValueSql("(newid())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_WebTube_recordId")
                .HasColumnName("recordId");
            entity.Property(e => e.Category)
                .HasMaxLength(100)
                .HasColumnName("category");
            entity.Property(e => e.DateTime)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_WebTube_datetime")
                .HasColumnType("datetime")
                .HasColumnName("dateTime");
            entity.Property(e => e.Note)
                .HasMaxLength(4000)
                .HasColumnName("note");
            entity.Property(e => e.ThumbnailDefaultHeight)
                .HasMaxLength(10)
                .HasColumnName("thumbnailDefaultHeight");
            entity.Property(e => e.ThumbnailDefaultUrl)
                .HasMaxLength(500)
                .HasColumnName("thumbnailDefaultUrl");
            entity.Property(e => e.ThumbnailDefaultWidth)
                .HasMaxLength(10)
                .HasColumnName("thumbnailDefaultWidth");
            entity.Property(e => e.ThumbnailHighHeight)
                .HasMaxLength(10)
                .HasColumnName("thumbnailHighHeight");
            entity.Property(e => e.ThumbnailHighUrl)
                .HasMaxLength(500)
                .HasColumnName("thumbnailHighUrl");
            entity.Property(e => e.ThumbnailHighWidth)
                .HasMaxLength(10)
                .HasColumnName("thumbnailHighWidth");
            entity.Property(e => e.ThumbnailMaxresHeight)
                .HasMaxLength(10)
                .HasColumnName("thumbnailMaxresHeight");
            entity.Property(e => e.ThumbnailMaxresUrl)
                .HasMaxLength(500)
                .HasColumnName("thumbnailMaxresUrl");
            entity.Property(e => e.ThumbnailMaxresWidth)
                .HasMaxLength(10)
                .HasColumnName("thumbnailMaxresWidth");
            entity.Property(e => e.ThumbnailMediumHeight)
                .HasMaxLength(10)
                .HasColumnName("thumbnailMediumHeight");
            entity.Property(e => e.ThumbnailMediumUrl)
                .HasMaxLength(500)
                .HasColumnName("thumbnailMediumUrl");
            entity.Property(e => e.ThumbnailMediumWidth)
                .HasMaxLength(10)
                .HasColumnName("thumbnailMediumWidth");
            entity.Property(e => e.ThumbnailStandardHeight)
                .HasMaxLength(10)
                .HasColumnName("thumbnailStandardHeight");
            entity.Property(e => e.ThumbnailStandardUrl)
                .HasMaxLength(500)
                .HasColumnName("thumbnailStandardUrl");
            entity.Property(e => e.ThumbnailStandardWidth)
                .HasMaxLength(10)
                .HasColumnName("thumbnailStandardWidth");
            entity.Property(e => e.VideoId)
                .HasMaxLength(50)
                .HasColumnName("videoId");
            entity.Property(e => e.VideoListId)
                .HasMaxLength(50)
                .HasColumnName("videoListId");
            entity.Property(e => e.WebTubeLink)
                .HasMaxLength(500)
                .HasColumnName("webTubeLink");
            entity.Property(e => e.WebTubeTitle)
                .HasMaxLength(500)
                .HasColumnName("webTubeTitle");
        });

        modelBuilder.Entity<WebTubeSeries>(entity =>
        {
            entity.HasKey(e => e.RecordId);

            entity.Property(e => e.RecordId)
                .HasDefaultValueSql("(newid())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_WebTubeSeries_recordId")
                .HasColumnName("recordId");
            entity.Property(e => e.DateTime)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_WebTubeSeries_datetime")
                .HasColumnType("datetime")
                .HasColumnName("dateTime");
            entity.Property(e => e.SeqNumber).HasColumnName("seqNumber");
            entity.Property(e => e.ThumbNailDefaultHeight)
                .HasMaxLength(10)
                .HasColumnName("thumbNailDefaultHeight");
            entity.Property(e => e.ThumbNailDefaultUrl)
                .HasMaxLength(100)
                .HasColumnName("thumbNailDefaultUrl");
            entity.Property(e => e.ThumbNailDefaultWidth)
                .HasMaxLength(10)
                .HasColumnName("thumbNailDefaultWidth");
            entity.Property(e => e.ThumbNailHighHeight)
                .HasMaxLength(10)
                .HasColumnName("thumbNailHighHeight");
            entity.Property(e => e.ThumbNailHighUrl)
                .HasMaxLength(100)
                .HasColumnName("thumbNailHighUrl");
            entity.Property(e => e.ThumbNailHighWidth)
                .HasMaxLength(10)
                .HasColumnName("thumbNailHighWidth");
            entity.Property(e => e.ThumbNailMaxresHeight)
                .HasMaxLength(10)
                .HasColumnName("thumbNailMaxresHeight");
            entity.Property(e => e.ThumbNailMaxresUrl)
                .HasMaxLength(100)
                .HasColumnName("thumbNailMaxresUrl");
            entity.Property(e => e.ThumbNailMaxresWidth)
                .HasMaxLength(10)
                .HasColumnName("thumbNailMaxresWidth");
            entity.Property(e => e.ThumbNailMediumHeight)
                .HasMaxLength(10)
                .HasColumnName("thumbNailMediumHeight");
            entity.Property(e => e.ThumbNailMediumUrl)
                .HasMaxLength(100)
                .HasColumnName("thumbNailMediumUrl");
            entity.Property(e => e.ThumbNailMediumWidth)
                .HasMaxLength(10)
                .HasColumnName("thumbNailMediumWidth");
            entity.Property(e => e.ThumbNailStandardHeight)
                .HasMaxLength(10)
                .HasColumnName("thumbNailStandardHeight");
            entity.Property(e => e.ThumbNailStandardUrl)
                .HasMaxLength(100)
                .HasColumnName("thumbNailStandardUrl");
            entity.Property(e => e.ThumbNailStandardWidth)
                .HasMaxLength(10)
                .HasColumnName("thumbNailStandardWidth");
            entity.Property(e => e.VideoId)
                .HasMaxLength(50)
                .HasColumnName("videoId");
            entity.Property(e => e.VideoTitle)
                .HasMaxLength(500)
                .HasColumnName("videoTitle");
            entity.Property(e => e.WebTubeId).HasColumnName("webTubeId");

            entity.HasOne(d => d.WebTube).WithMany(p => p.WebTubeSeries)
                .HasForeignKey(d => d.WebTubeId)
                .HasConstraintName("FK_WebTubeSeries_WebTube");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}