// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebFamily.Models;

public partial class WebTubeSeries
{
    public Guid RecordId { get; set; }

    public Guid WebTubeId { get; set; }

    public string VideoId { get; set; }

    public string VideoTitle { get; set; }

    public string ThumbNailDefaultUrl { get; set; }

    public string ThumbNailDefaultWidth { get; set; }

    public string ThumbNailDefaultHeight { get; set; }

    public string ThumbNailMediumUrl { get; set; }

    public string ThumbNailMediumWidth { get; set; }

    public string ThumbNailMediumHeight { get; set; }

    public string ThumbNailHighUrl { get; set; }

    public string ThumbNailHighWidth { get; set; }

    public string ThumbNailHighHeight { get; set; }

    public int SeqNumber { get; set; }

    public DateTime DateTime { get; set; }

    public string ThumbNailStandardUrl { get; set; }

    public string ThumbNailMaxresUrl { get; set; }

    public string ThumbNailStandardWidth { get; set; }

    public string ThumbNailStandardHeight { get; set; }

    public string ThumbNailMaxresWidth { get; set; }

    public string ThumbNailMaxresHeight { get; set; }

    public virtual WebTube WebTube { get; set; }
}