// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebFamily.Models;

public partial class WebTube
{
    public Guid RecordId { get; set; }

    public string WebTubeLink { get; set; }

    public string Note { get; set; }

    public string Category { get; set; }

    public string VideoId { get; set; }

    public string VideoListId { get; set; }

    public string WebTubeTitle { get; set; }

    public DateTime DateTime { get; set; }

    public string ThumbnailDefaultUrl { get; set; }

    public string ThumbnailMediumUrl { get; set; }

    public string ThumbnailHighUrl { get; set; }

    public string ThumbnailStandardUrl { get; set; }

    public string ThumbnailMaxresUrl { get; set; }

    public string ThumbnailDefaultWidth { get; set; }

    public string ThumbnailDefaultHeight { get; set; }

    public string ThumbnailMediumWidth { get; set; }

    public string ThumbnailMediumHeight { get; set; }

    public string ThumbnailHighWidth { get; set; }

    public string ThumbnailHighHeight { get; set; }

    public string ThumbnailStandardWidth { get; set; }

    public string ThumbnailStandardHeight { get; set; }

    public string ThumbnailMaxresWidth { get; set; }

    public string ThumbnailMaxresHeight { get; set; }

    public virtual ICollection<WebTubeSeries> WebTubeSeries { get; set; } = new List<WebTubeSeries>();
}